---
title: "Gexpr clustering"
author: "Sébastien Renaut (sebastien.renaut@criucpq.ulaval.ca)"
date: "`r Sys.Date()`"
output:
  html_document:
    number_sections: F
params:
  datapath: 'C:/Users/renseb01/Documents/clustering_gexpr/data'
  outputpath: 'C:/Users/renseb01/Documents/clustering_gexpr/results/April2025'
  repo: 'C:/Users/renseb01/Documents/clustering'
---



```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = params$repo)
knitr::opts_chunk$set(echo = F)
library(ggplot2)
library(patchwork)
library(factoextra)
library(FactoMineR)
library(cluster)
library(DESeq2)
library(dplyr)
library(tidyr)
library(RColorBrewer)
library(biomaRt)
library(org.Hs.eg.db)
library(ComplexUpset)
library(survival)
library(survminer)
library(readxl)
```



```{r data}
clinical_bigtable = read.csv(file.path(params$repo,'../rnaseq/data/clinical_bigtable_v3.csv'), check.names = F)

 #3. get bulkRNAseq data
  txi = readRDS(file.path(params$repo,'../rnaseq/lord_kallisto/txi.rds'))

  #bulk = as.matrix(txi$abundance)
  bulk <- round(txi$counts)
  rownames(bulk) = sapply(strsplit(rownames(bulk), ".",fixed = T), "[",1) #matrix. genes X cells. Floats (Counts). Raw abundance (so TPM)
  colnames(bulk) = sapply(strsplit(colnames(bulk), ".",fixed = T), "[",5)

  bulk_vst = vst(bulk)
```

```{r choose specific genes}
#keep some candidate from some study (Wilkerson MD, et al. Differential pathogenesis of lung adenocarcinoma subtypes involving sequence mutations, copy number, chromosomal instability, and methylation. PLoS ONE. 2012;7:e36530. doi: 10.1371/journal.pone.0036530.)
Raz2008 = c('WNT3A','ERBB3','LCK','RND3')#Raz et al. 2008 A Multigene Assay Is Prognostic of Survival in Patients with Early-Stage Lung Adenocarcinoma
Wilkerson2012 = c('SFTPC','DMBT1','FOLR1','DUSP4','FGL1','TDG','PLAU','G0S2','CXCL10') #Wilkerson MD, et al 2012
Bianchi2007 = c('NUDCD1','E1F','HOXB7','MCM6','SERPINB5','E2F4','HFPG2','SF3B1','RRM2','SCGB3A1') # Bianchi2007
Kratz2012 = c('BAG1','BRCA1','CDC6','CDK2AP1','ERBB3','FUT3','IL11','LCK','RND3','SH3BGR','WNT3A','ESD','TBP','YAP1') # Kratz 2012 low/med/high
Der2014 = c('ATP1B1','TRIM14','FAM64A','FOSL2','HEXIM1','MB','L1CAM','UMPS','EDN3','STMN2','MYT1L','IKBKAP','MLANA','MDM2','ZNF236') # Der2014 low/high
Shukla2016 = c('RHOV','CD109','FRRS1','LINC00941') #Shukla et al. 2016 Development of a RNA-Seq Based Prognostic Signature in Lung Adenocarcinoma
Wistuba2013 = c('ASPM','CDCA8','MCM10','FOXM1','CDC20','CDKN3','BIRC5','DLGAP5','KIF20A','BUB1B','PRC1','TK1','CEP55','PBK','RAD54L','NUSAP1','RRM2','KIAA0101','ORC6L','RAD51','CENPM','SKA1','CENPF','KIF11','PTTG1','CDC2','DTL','PLK1','CDCA3','ASF1B','TOP2A')
Peinado2022 = c('APOBEC3B','GOLM1','FAM117A','KCNQ1OT1','PCDHB2','USP43') #Peinado-Serrano, Javier, et al. "A six-gene prognostic and predictive radiotherapy-based signature for early and locally advanced stages in non-small-cell lung cancer." Cancers 14.9 (2022): 2054.
Biswas2019 = c('ANLN','ASPM','CDCA4','ERRFI1','FURIN','GOLGA8A','ITGA6','JAG1','LRP12','MAFF','MRPS17','PLK1','PNP','PPP1R13L','PRKCA','PTTG1','PYGB','RPP25','SCPEP1','SLC46A3','SNX7','TPBG','XBP1')



Lamaze2024 = read_xlsx(file.path(params$datapath,"Lamaze_genes_predictors.xlsx"))
Lamaze2024 = Lamaze2024$Symbol[Lamaze2024$bioortho ==T]
#Lamaze2024 = Lamaze2024$Symbol[Lamaze2024$bio30 ==T]

#Validation of a Proliferation-Based Expression Signature as Prognostic Marker in Early Stage Lung Adenocarcinoma 
predictors = list(c('top5','SFTPC'),Bianchi2007,Kratz2012,Der2014,Wilkerson2012,Raz2008,Shukla2016,Wistuba2013,Peinado2022,Lamaze2024,Biswas2019)
names(predictors) = c('top5%','Bianchi 2007','Kratz 2012','Der 2014','Wilkerson 2012','Raz 2008','Shukla 2016','Wistuba 2013','Peinado-Serrano 2022','Lamaze 2024','Biswas 2019')
sil_plots = list() 

#conversion from ENTREZID -> Ensembl
for(i in 1:11) {
  conversion = biomaRt::select(org.Hs.eg.db, keys = predictors[[i]], columns = c("ENTREZID", "SYMBOL","ENSEMBL"), keytype = "SYMBOL")
  conversion = conversion[!is.na(conversion$ENSEMBL),]
  conversion = conversion[!duplicated(conversion$ENSEMBL), c(1,3)]
  #conversion$cat = c(rep('bronchoid',3),rep('magnoid',3),rep('squamoid',3))
  
  #bulk_vst_variable = bulk_vst[variance_genes > cutoff, ]
  bulk_vst_variable_tumeur = t(bulk_vst[,grep('Tumeur',colnames(bulk_vst))])
  bulk_vst_variable_tumeur = bulk_vst_variable_tumeur[,colnames(bulk_vst_variable_tumeur) %in% conversion$ENSEMBL]

  print(paste0(' --- ', i ))
  print(conversion)
  
  #conversion = conversion[order(conversion$SYMBOL),]   
  #bulk_vst_variable_tumeur = bulk_vst_variable_tumeur[,order(colnames(bulk_vst_variable_tumeur))]
  #colnames(bulk_vst_variable_tumeur) = conversion$SYMBOL
  if(i == 1) {
    variance_genes = apply(bulk_vst[,grep('Tumeur',colnames(bulk_vst))],1,var)
    cutoff = quantile(variance_genes,seq(0,1,by = 0.05))[20]
    bulk_vst_variable = bulk_vst[variance_genes > cutoff, ]
    bulk_vst_variable_tumeur = t(bulk_vst_variable[,grep('Tumeur',colnames(bulk_vst_variable))])
    
    sil_plots[[i]] = fviz_nbclust(bulk_vst_variable_tumeur, kmeans, method = "silhouette")
    
    set.seed(123456)
    k3 = kmeans(bulk_vst_variable_tumeur,3,nstart = 100)
    #k4 = kmeans(bulk_vst_variable_tumeur,4,nstart = 100)

    pca_data = PCA(bulk_vst_variable_tumeur,scale = F, graph = F,ncp = 50)
    
    cluster_table = data.frame(`Record ID` = sapply(strsplit(rownames(bulk_vst_variable_tumeur), "_",fixed = T), "[",3),
                               k2 =  as.factor(kmeans(bulk_vst_variable_tumeur,2,nstart = 100)$cluster),
                               k3 =  as.factor(k3$cluster),
                               k4 =  as.factor(kmeans(bulk_vst_variable_tumeur,4,nstart = 100)$cluster),
                               
                               k2pca =  as.factor(kmeans(pca_data$ind$coord,2,nstart = 100)$cluster),
                               k3pca =  as.factor(kmeans(umap::umap(pca_data$ind$coord)$layout,3,nstart = 100)$cluster),
                               k4pca =  as.factor(kmeans(pca_data$ind$coord,4,nstart = 100)$cluster),
                               check.names = F)
  }
  
  if(i >1){
    k = 2
    sil_plots[[i]] = fviz_nbclust(bulk_vst_variable_tumeur, kmeans, method = "silhouette")
    marker_based_signatures = kmeans(bulk_vst_variable_tumeur,k,nstart = 100)
   # if((i == 3) | (i == 5)) marker_based_signatures = kmeans(bulk_vst_variable_tumeur,3,nstart = 100)
  
    marker_based_signatures$cluster[marker_based_signatures$cluster==1] = paste0('cluster 1_',names(predictors)[[i]])
    marker_based_signatures$cluster[marker_based_signatures$cluster==2] = paste0('cluster 2_',names(predictors)[[i]])
    marker_based_signatures$cluster[marker_based_signatures$cluster==3] = paste0('cluster 3_',names(predictors)[[i]])
  

    if(i == 2) cluster_table$Bianchi2007 =  as.factor(marker_based_signatures$cluster)
    if(i == 3) cluster_table$Kratz2012 =  as.factor(marker_based_signatures$cluster)
    if(i == 4) cluster_table$Der2014 =  as.factor(marker_based_signatures$cluster)
    if(i == 5) cluster_table$Wilkerson2012 =  as.factor(marker_based_signatures$cluster)
    if(i == 6) cluster_table$Raz2008 =  as.factor(marker_based_signatures$cluster)
    if(i == 7) cluster_table$Shukla2016 =  as.factor(marker_based_signatures$cluster)
    if(i == 8) cluster_table$Wistuba2013 =  as.factor(marker_based_signatures$cluster)
    if(i == 9) cluster_table$Peinado2022 =  as.factor(marker_based_signatures$cluster)
    if(i == 10) cluster_table$Lamaze2024 =  as.factor(marker_based_signatures$cluster)
    if(i == 11) cluster_table$Biswas2019 =  as.factor(marker_based_signatures$cluster)
  
    #cluster_table$random =  as.factor(sample(c('cluster 1_random N','cluster 2_random N'),515,replace =T))
    #cluster_table$random =  as.factor(sample(c('cluster 1_random N','cluster 2_random N','cluster 3_random N'),515,replace =T))
    #cluster_table$random =  as.factor(sample(c('cluster 1_random 3','cluster 2_random 3','cluster 3_random 3'),515,replace =T))

    #one every cluster is calculated, just put everything together.
    if(i == 11) {
      clinical_cluster = merge(cluster_table,clinical_bigtable,by = 'Record ID')
      print(paste0('Dimensions of,',nrow(clinical_cluster)))
      k2_grouped = clinical_cluster %>% group_by(k2) %>% summarise(pfs = mean(`Follow-up_PFS (2022)`,na.rm =T), n = n())
      k3_grouped = clinical_cluster %>% group_by(k3) %>% summarise(pfs = median(`Follow-up_PFS (2022)`,na.rm =T), n = n())
      k4_grouped = clinical_cluster %>% group_by(k4) %>% summarise(pfs = mean(`Follow-up_PFS (2022)`,na.rm =T), n = n())
      
      kwistuba_grouped = clinical_cluster %>% group_by(Wistuba2013) %>% summarise(pfs = mean(`Follow-up_PFS (2022)`,na.rm =T), n = n())
      kshukla_grouped = clinical_cluster %>% group_by(Shukla2016) %>% summarise(pfs = mean(`Follow-up_PFS (2022)`,na.rm =T), n = n())
      kraz_grouped = clinical_cluster %>% group_by(Raz2008) %>% summarise(pfs = mean(`Follow-up_PFS (2022)`,na.rm =T), n = n())
      
      kwilkerson_grouped = clinical_cluster %>% group_by(Wilkerson2012) %>% summarise(pfs = mean(`Follow-up_PFS (2022)`,na.rm =T), n = n())
      kbianchi_grouped = clinical_cluster %>% group_by(Bianchi2007) %>% summarise(pfs = mean(`Follow-up_PFS (2022)`,na.rm =T), n = n())
      kkratz_grouped = clinical_cluster %>% group_by(Kratz2012) %>% summarise(pfs = mean(`Follow-up_PFS (2022)`,na.rm =T), n = n())
      kder_grouped = clinical_cluster %>% group_by(Der2014) %>% summarise(pfs = mean(`Follow-up_PFS (2022)`,na.rm =T), n = n())
      
      kpeinado_grouped = clinical_cluster %>% group_by(Peinado2022) %>% summarise(pfs = mean(`Follow-up_PFS (2022)`,na.rm =T), n = n())
      lamaze_grouped = clinical_cluster %>% group_by(Lamaze2024) %>% summarise(pfs = mean(`Follow-up_PFS (2022)`,na.rm =T), n = n())
      biswas_grouped = clinical_cluster %>% group_by(Biswas2019) %>% summarise(pfs = mean(`Follow-up_PFS (2022)`,na.rm =T), n = n())
      #ran_grouped = clinical_cluster %>% group_by(random) %>% summarise(pfs = mean(`Follow-up_PFS (2022)`,na.rm =T), n = n())
      }
    }
  }
```



```{r heatmap,eval = F}
heatmap(t(scale(bulk_vst_variable_tumeur)),scale = 'none')
```



```{r survival}
clinical_cluster$`Tumor volume\n(cm3)` = NA
volume_quants = quantile(clinical_cluster$Pathology_Tumor_size_tumxyz)

clinical_cluster$`Tumor volume\n(cm3)`[clinical_cluster$Pathology_Tumor_size_tumxyz <= volume_quants[2]] = '<5.6'
clinical_cluster$`Tumor volume\n(cm3)`[(clinical_cluster$Pathology_Tumor_size_tumxyz > volume_quants[2]) & (clinical_cluster$Pathology_Tumor_size_tumxyz <= volume_quants[3])] = '5.6-12'
clinical_cluster$`Tumor volume\n(cm3)`[(clinical_cluster$Pathology_Tumor_size_tumxyz > volume_quants[3]) & (clinical_cluster$Pathology_Tumor_size_tumxyz <= volume_quants[4])] = '12-26.3'
clinical_cluster$`Tumor volume\n(cm3)`[clinical_cluster$Pathology_Tumor_size_tumxyz > volume_quants[4]] = '>26.3'
clinical_cluster$`Tumor volume\n(cm3)` = factor(clinical_cluster$`Tumor volume\n(cm3)`,levels = unique(clinical_cluster$`Tumor volume\n(cm3)`)[c(1,4,2,3)])

#
clinical_cluster$Age = NA
clinical_cluster$Age[clinical_cluster$`Profil_visit_history_Age at diagnosis`>= 71] = '>75'
clinical_cluster$Age[clinical_cluster$`Profil_visit_history_Age at diagnosis`< 60] = '<60 years old'
clinical_cluster$Age[clinical_cluster$`Profil_visit_history_Age at diagnosis`>= 60 & clinical_cluster$`Profil_visit_history_Age at diagnosis` < 65] = '60-65'
clinical_cluster$Age[clinical_cluster$`Profil_visit_history_Age at diagnosis`>= 65 & clinical_cluster$`Profil_visit_history_Age at diagnosis` < 71] = '65-71'
clinical_cluster$Age = factor(clinical_cluster$Age,levels = unique(clinical_cluster$Age)[c(5,4,1,2)])

#
clinical_cluster$`Pack year` = NA
clinical_cluster$`Pack year`[clinical_cluster$`Profil_visit_history_Pack/Year`<23] = '<23pk/yr'
clinical_cluster$`Pack year`[clinical_cluster$`Profil_visit_history_Pack/Year`>=49] = '>49'
clinical_cluster$`Pack year`[(clinical_cluster$`Profil_visit_history_Pack/Year`>=23) & (clinical_cluster$`Profil_visit_history_Pack/Year`<38)] = '23-38'
clinical_cluster$`Pack year`[(clinical_cluster$`Profil_visit_history_Pack/Year`>=38) & (clinical_cluster$`Profil_visit_history_Pack/Year`<49)] = '38-49'
clinical_cluster$`Pack year` = factor(clinical_cluster$`Pack year`,levels = unique(clinical_cluster$`Pack year`)[c(4,3,2,5)])

#
clinical_cluster$os = clinical_cluster$`Follow-up_O.S. (2022)`
clinical_cluster$status = ifelse(clinical_cluster$`Profil_visit_history_Vital status` == "Alive",0,1)
clinical_cluster$pfs = clinical_cluster$`Follow-up_PFS (2022)`/365
clinical_cluster$Sex = clinical_cluster$`Profil_visit_history_Sex at birth`
clinical_cluster$Sex = factor(clinical_cluster$Sex,levels = c('Female','Male'))


clinical_cluster$Grade = clinical_cluster$Pathology_Tumor_Grade 
clinical_cluster$Grade = paste0('G',clinical_cluster$Grade)
clinical_cluster$Grade[clinical_cluster$Grade  =='Gn/a'] = 'unknown'

#clinical_cluster$Grade[clinical_cluster$Grade  ==''] = 'unknown'
#clinical_cluster$Grade[clinical_cluster$Grade  =='G4 undifferentiated'] = 'G3 poorly differentiated'
#clinical_cluster$Grade = sapply(strsplit(clinical_cluster$Grade, " ",fixed = T),"[",1)
#clinical_cluster$Grade[clinical_cluster$Grade == 'G3'] = 'G3-4' 
clinical_cluster$Grade = factor(clinical_cluster$Grade)

#clinical_cluster$`Predominant\nfeature`[clinical_cluster$`Predominant\nfeature` == 'Micropapillary'] = 'Micropap.'
#clinical_cluster$`Predominant\nfeature` = factor(clinical_cluster$`Predominant\nfeature`, levels = c('Lepidic','Acinar','Micropap.','Papillary','Solid','unknown'))


###
clinical_cluster$`Predominant\nfeature` = 'Intermediate\n(Acinar|Pap)'
clinical_cluster$`Predominant\nfeature`[clinical_cluster$`Pathology_Tumor_Predominant feature` == 'Lepidic'] = 'Lepidic (low)'
clinical_cluster$`Predominant\nfeature`[clinical_cluster$`Pathology_Tumor_Predominant feature` == ''] = 'unknown'
clinical_cluster$`Predominant\nfeature`[(clinical_cluster$`Pathology_Tumor_Solid %` >= 20) | (clinical_cluster$`Pathology_Tumor_Micropapillary %` >= 20) | (clinical_cluster$`Pathology_Tumor_Fused glands %` >= 20) | (clinical_cluster$`Pathology_Tumor_Cribriform %` >= 20)] = 'High (Solid | \nMpap|Complex)'
clinical_cluster$`Predominant\nfeature` = factor(clinical_cluster$`Predominant\nfeature`, levels = c('Lepidic (low)','Intermediate\n(Acinar|Pap)','High (Solid | \nMpap|Complex)','unknown'))
###


clinical_cluster$`Smoking\nstatus` = clinical_cluster$`Profil_visit_history_Smoking status`
clinical_cluster$`Smoking\nstatus` = gsub(' smoker','',clinical_cluster$`Smoking\nstatus`)
clinical_cluster$`Smoking\nstatus` = gsub('Smoker','Current',clinical_cluster$`Smoking\nstatus`)
clinical_cluster$`Smoking\nstatus` = gsub('Passive','Non',clinical_cluster$`Smoking\nstatus`)
clinical_cluster$`Smoking\nstatus` = factor(clinical_cluster$`Smoking\nstatus`,levels = c('Non','Former','Current'))

clinical_cluster$k2 = factor(clinical_cluster$k2,k2_grouped[[1]][order(k2_grouped$pfs,decreasing = T)])
clinical_cluster$k3 = factor(clinical_cluster$k3,k3_grouped[[1]][order(k3_grouped$pfs,decreasing = T)])
clinical_cluster$k4 = factor(clinical_cluster$k4,k4_grouped[[1]][order(k4_grouped$pfs,decreasing = T)])

#percentage of tumor.
clinical_cluster$`Pathology_Tumor_Percentage of Tumor`[is.na(clinical_cluster$`Pathology_Tumor_Percentage of Tumor`)] = mean(clinical_cluster$`Pathology_Tumor_Percentage of Tumor`,na.rm = T)
clinical_cluster$`Percentage\nof Tumor` = '<35% tumor'
clinical_cluster$`Percentage\nof Tumor`[(clinical_cluster$`Pathology_Tumor_Percentage of Tumor` >= 35) & (clinical_cluster$`Pathology_Tumor_Percentage of Tumor` < 55)] = '35-55%'
clinical_cluster$`Percentage\nof Tumor`[(clinical_cluster$`Pathology_Tumor_Percentage of Tumor` >= 55) & (clinical_cluster$`Pathology_Tumor_Percentage of Tumor` < 75)] = '55-75%'
clinical_cluster$`Percentage\nof Tumor`[clinical_cluster$`Pathology_Tumor_Percentage of Tumor` >= 75] = '>75%'
clinical_cluster$`Percentage\nof Tumor` = factor(clinical_cluster$`Percentage\nof Tumor`,levels = unique(clinical_cluster$`Percentage\nof Tumor`)[c(3,1,2,4)])

#random grouping are a bit odd, because they are non-significant.
#clinical_cluster$random2 = factor(clinical_cluster$random2,ran2_grouped[[1]][order(ran2_grouped$pfs,decreasing = T)])
#clinical_cluster$random = factor(clinical_cluster$random,ran_grouped[[1]][order(ran_grouped$pfs,decreasing = T)])

clinical_cluster$Bianchi2007 = factor(clinical_cluster$Bianchi2007,kbianchi_grouped[[1]][order(kbianchi_grouped$pfs,decreasing = T)])
clinical_cluster$Kratz2012 = factor(clinical_cluster$Kratz2012,kkratz_grouped[[1]][order(kkratz_grouped$pfs,decreasing = T)])
clinical_cluster$Der2014 = factor(clinical_cluster$Der2014,kder_grouped[[1]][order(kder_grouped$pfs,decreasing = T)])
clinical_cluster$Wilkerson2012 = factor(clinical_cluster$Wilkerson2012,kwilkerson_grouped[[1]][order(kwilkerson_grouped$pfs,decreasing = T)])

clinical_cluster$Wistuba2013 = factor(clinical_cluster$Wistuba2013,kwistuba_grouped[[1]][order(kwistuba_grouped$pfs,decreasing = T)])
clinical_cluster$Shukla2016 = factor(clinical_cluster$Shukla2016,kshukla_grouped[[1]][order(kshukla_grouped$pfs,decreasing = T)])
clinical_cluster$Raz2008 = factor(clinical_cluster$Raz2008,kraz_grouped[[1]][order(kraz_grouped$pfs,decreasing = T)])
clinical_cluster$Peinado2022 = factor(clinical_cluster$Peinado2022,kpeinado_grouped[[1]][order(kpeinado_grouped$pfs,decreasing = T)])
clinical_cluster$Lamaze2024 = factor(clinical_cluster$Lamaze2024,lamaze_grouped[[1]][order(lamaze_grouped$pfs,decreasing = T)])
clinical_cluster$Biswas2019 = factor(clinical_cluster$Biswas2019,biswas_grouped[[1]][order(biswas_grouped$pfs,decreasing = T)])

clinical_cluster$Stage = clinical_cluster$`Pathology_Tumor_Stage pathologic`
clinical_cluster$Stage[clinical_cluster$Stage %in% c('1A','1A1','1A2','1A3')] = '1A'
#clinical_cluster$Stage[clinical_cluster$Stage %in% c('1A','1A1')] = '1A'

clinical_cluster$Stage[clinical_cluster$Stage %in% c('1B')] = '1B'
clinical_cluster$Stage[clinical_cluster$Stage %in% c('2A')] = '2A'
clinical_cluster$Stage[clinical_cluster$Stage %in% c('2B')] = '2B'
clinical_cluster$Stage[clinical_cluster$Stage %in% c('3A')] = '3-4'
clinical_cluster$Stage[clinical_cluster$Stage %in% c('','0')] = '3-4'
clinical_cluster$Stage[clinical_cluster$Stage %in% c('3B','4A')] = '3-4'
clinical_cluster$Stage = factor(clinical_cluster$Stage)

#
coxfit1 = coxph(Surv(pfs,status) ~ k2, data = clinical_cluster, x = TRUE)
gtsummary::tbl_regression(coxfit1, exponentiate = TRUE)

pfits = list()

palette = c(brewer.pal(9,'Set1'),brewer.pal(5,'Set3'))

#
fit = survfit(Surv(pfs, status) ~ k2, data = clinical_cluster[clinical_cluster$pfs<10,])
pfits[[1]] = ggsurvplot(fit,pval = T,conf.int = F,legend.title = "k = 2",legend.labs = c('cluster 2 (high survival)','cluster 1 (low survival)'),xlab = c('Time (years)'),palette = palette[2:1] )$plot+ geom_vline(xintercept = 5,linetype = 'dashed')

fit = survfit(Surv(pfs, status) ~ k3, data = clinical_cluster[clinical_cluster$pfs<10,])
pfits[[2]] = ggsurvplot(fit,pval = T,conf.int = F,legend.title = "k = 3",legend.labs = c('cluster 1','cluster 2','cluster 3') ,xlab = c('Time (years)'),palette = palette[c(4:5,1)])$plot + geom_vline(xintercept = 5,linetype = 'dashed')

fit = survfit(Surv(pfs, status) ~ k4, data = clinical_cluster[clinical_cluster$pfs<10,])
pfits[[3]] = ggsurvplot(fit,pval = T,conf.int = F,legend.title = "k = 4",legend.labs = c('cluster 2','cluster 1','cluster 4','cluster 3'),xlab = c('Time (years)'),palette = palette[c(6:8,1)])$plot+ geom_vline(xintercept = 5,linetype = 'dashed')

fit = survfit(Surv(pfs, status) ~ Stage, data = clinical_cluster[clinical_cluster$pfs<10,])
pfits[[4]] = ggsurvplot(fit,pval = T,conf.int = F,legend.title = "Pathological staging",xlab = c('Time (years)'),palette = palette[c(11:14,1)])$plot + geom_vline(xintercept = 5,linetype = 'dashed')#legend.labs = c("1A", "1B",'2A','2B','3-4')

#fit = survfit(Surv(pfs, status) ~ random, data = clinical_cluster)
#ggsurvplot(fit,pval = T,conf.int = T)$plot

(pfits[[4]] + pfits[[1]]) / (pfits[[2]] + pfits[[3]]) #
```

```{r hazard ratios}
#
hazard_summarised = NULL
factors = c('Tumor volume\n(cm3)','Grade','Predominant\nfeature','Stage','Pack year','Smoking\nstatus','Age','Sex',
            'Bianchi2007','Kratz2012','Der2014','Wilkerson2012','Wistuba2013','Shukla2016','Raz2008','Peinado2022','Lamaze2024','Biswas2019',paste('k',k,sep = ''))


#loop
for(i in 1:length(factors)){
 
  dataset = clinical_cluster[clinical_cluster$pfs<10,colnames(clinical_cluster) %in% c('pfs','status', factors[i])]
  colnames(dataset)[colnames(dataset) == factors[i]] = 'zzz' 
  
  coxfit = coxph(Surv(pfs,status) ~ zzz, data = dataset, x = TRUE)
  coxfit_summary = summary(coxfit)
  rownames(coxfit_summary$conf.int) = gsub('zzz',factors[i],rownames(coxfit_summary$conf.int))
  
  #better info
  coxfit_summary2 = cbind(rbind(c(1,1,1),coxfit_summary$conf.int[,c(1,3,4)]),c(1,coxfit_summary$coefficients[,5]))
  rownames(coxfit_summary2)[1:2] = c(paste0(factors[i],levels(clinical_cluster[,colnames(clinical_cluster) %in% factors[i]])[1]),
                                     rownames(coxfit_summary$conf.int)[1])
  
  coxfit_summary2 = as.data.frame(coxfit_summary2)
  coxfit_summary2$n = table(dataset$zzz)
  coxfit_summary2$names = factors[i]
  coxfit_summary2$catego = rownames(coxfit_summary2)
  coxfit_summary2$catego = gsub(factors[i],'',coxfit_summary2$catego,fixed = T)
  coxfit_summary2 = coxfit_summary2[nrow(coxfit_summary2):1,]
  
  if(i == 1 ) hazard_summarised = coxfit_summary2
  if(i > 1)   hazard_summarised = rbind(hazard_summarised,coxfit_summary2)
  
  #rownames(coxfit_summary$conf.int) = gsub('zzz',factors[i],rownames(coxfit_summary$conf.int))
  }


colnames(hazard_summarised)[1:4] = c('HR','low','high','pval')
hazard_summarised$rownames = factor(rownames(hazard_summarised),levels = rownames(hazard_summarised))
hazard_summarised$high[hazard_summarised$high>10] = 9.99
hazard_summarised = hazard_summarised[hazard_summarised$catego!= 'unknown',]

hazard_summarised$catego[hazard_summarised$catego==1] = 'cluster 1'
hazard_summarised$catego[hazard_summarised$catego==2] = 'cluster 2'
hazard_summarised$catego[hazard_summarised$catego==3] = 'cluster 3'

hazard_summarised$names[hazard_summarised$names=='k2'|hazard_summarised$names=='k3'] = 'top25% variable' 
hazard_summarised$names[hazard_summarised$names=='Bianchi2007'] = 'Bianchi 2007' 
hazard_summarised$names[hazard_summarised$names=='Der2014'] = 'Der 2014' 
hazard_summarised$names[hazard_summarised$names=='Kratz2012'] = 'Kratz 2012'
hazard_summarised$names[hazard_summarised$names=='Wilkerson2012'] = 'Wilkerson 2012'
hazard_summarised$names[hazard_summarised$names=='Wistuba2013'] = 'Wistuba 2013'
hazard_summarised$names[hazard_summarised$names=='Shukla2016'] = 'Shukla 2016'
hazard_summarised$names[hazard_summarised$names=='Raz2008'] = 'Raz 2008'
hazard_summarised$names[hazard_summarised$names=='Peinado2022'] = 'Peinado 2022'
hazard_summarised$names[hazard_summarised$names=='Lamaze2024'] = 'Lamaze 2024'
hazard_summarised$names[hazard_summarised$names=='Biswas2019'] = 'Biswas 2019'

hazard_summarised$catego_fac = factor(hazard_summarised$catego,levels = hazard_summarised$catego)

#k = 3 
if(k ==3){
hazard_summarised$catego[c(1,4,7,10,13,16,19,22,25,28)+25] = gsub('cluster [1-9]','cluster high',hazard_summarised$catego[c(1,4,7,10,13,16,19,22,25,28)+25])
hazard_summarised$catego[c(1,4,7,10,13,16,19,22,25,28)+26] = gsub('cluster [1-9]','cluster med',hazard_summarised$catego[c(1,4,7,10,13,16,19,22,25,28)+26])
hazard_summarised$catego[c(1,4,7,10,13,16,19,22,25,28)+27] = gsub('cluster [1-9]','cluster reference',hazard_summarised$catego[c(1,4,7,10,13,16,19,22,25,28)+27])
}

#k=2
if(k ==2){
hazard_summarised$catego[c(1,3,5,7,9,11,13,15,17,19)+25] = gsub('cluster [1-9]','cluster high',hazard_summarised$catego[c(1,3,5,7,9,11,13,15,17,19)+25])
hazard_summarised$catego[c(1,3,5,7,9,11,13,15,17,19)+26] = gsub('cluster [1-9]','cluster reference',hazard_summarised$catego[c(1,3,5,7,9,11,13,15,17,19)+26])
}

#hazard_summarised$catego[hazard_summarised$catego == 'cluster high'] = 'cluster high_top25% variable'
#hazard_summarised$catego[hazard_summarised$catego == 'cluster med'] = 'cluster med_top25% variable'
#hazard_summarised$catego[hazard_summarised$catego == 'cluster reference'] = 'cluster reference_top25% variable'
  
hazard_summarised$catego = factor(hazard_summarised$catego,levels = hazard_summarised$catego)

hazard_summarised = hazard_summarised[nrow(hazard_summarised):1,]

hazard_summarised$names = factor(hazard_summarised$names,levels = unique(hazard_summarised$names))

hazard_summarised$pvalue = as.character(signif(hazard_summarised$pval,2))
hazard_summarised$pvalue[hazard_summarised$pvalue ==1] = 'Reference'
hazard_summarised$ntext = paste0('n = ', hazard_summarised$n)

#
#hazard_summarised$catego2 = as.character(hazard_summarised$catego)

#
gexpr_factors = c('top25% variable','Bianchi 2007','Der 2014','Kratz 2012','Wilkerson 2012','gWistuba 2013','Shukla 2016','Raz 2008','Peinado 2022','Biswas 2019')
hazard_summarised_clin = hazard_summarised[hazard_summarised$names %in% c('Smoking\nstatus','Sex','Age','Pack year'), ]
hazard_summarised_patho = hazard_summarised[hazard_summarised$names %in% c('Tumor volume\n(cm3)','Stage','Grade','Predominant\nfeature'), ]
hazard_summarised_gexpr = hazard_summarised[hazard_summarised$names %in% gexpr_factors,]

#reorder HR for the plots (k==3)
for(i in 1:10){
  temp = hazard_summarised_gexpr[hazard_summarised_gexpr$names == gexpr_factors[i],colnames(hazard_summarised_gexpr) %in% c('HR','low','high','pval','n')] 
  temp = temp[order(temp$HR),]
  hazard_summarised_gexpr[hazard_summarised_gexpr$names == gexpr_factors[i],colnames(hazard_summarised_gexpr) %in% c('HR','low','high','pval','n')] = temp
}


#keep the names the same, but we add extra spaces so that they are 'different' for tick marks during plotting.
if(k == 2) hazard_summarised_gexpr$catego_renamed = c('cluster 1','cluster 2')
if(k == 3) hazard_summarised_gexpr$catego_renamed = c('cluster 1','cluster 2','cluster 3')

for(i in 1:8){
  if(k ==2) hazard_summarised_gexpr$catego_renamed[(i*2 +1):(i*2 +2)] = paste0(paste0(rep(' ',i),collapse = ''),hazard_summarised_gexpr$catego_renamed[(i*2 + 1):(i*2 + 2)])
  if(k ==3) hazard_summarised_gexpr$catego_renamed[(i*3 +1):(i*3 +3)] = paste0(paste0(rep(' ',i),collapse = ''),hazard_summarised_gexpr$catego_renamed[(i*3 + 1):(i*3 + 3)])
}

hazard_summarised_gexpr$catego_renamed = factor(hazard_summarised_gexpr$catego_renamed,levels = hazard_summarised_gexpr$catego_renamed[nrow(hazard_summarised_gexpr):1])



#rectangle colors
rects_clin = data.frame(ystart = c(0.5,4.5,7.5,11.5), yend = c(4.5,7.5,11.5,13.5), 
         col = c('a','b','a','b'))

rects_path = data.frame(ystart = c(0.5,4.5,7.5,10.5), yend = c(4.5,7.5,10.5,15.5), 
         col = c('a','b','a','b'))

rects_Gxpr3 =  data.frame(ystart = c(0.5,3.5,6.5,9.5,12.5,15.5,18.5,21.5,24.5), yend =  c(3.5,6.5,9.5,12.5,15.5,18.5,21.5,24.5,27.5), 
         col = c('a','b','a','b','a','b','a','b','a'))

rects_Gxpr2 =  data.frame(ystart = c(0.5,2.5,4.5,6.5,8.5,10.5,12.5,14.5,16.5), yend =  c(2.5,4.5,6.5,8.5,10.5,12.5,14.5,16.5,18.5), 
         col = c('a','b','a','b','a','b','a','b','a'))

rects_Gxpr = list(1,rects_Gxpr2,rects_Gxpr3)

#plot
predictor_clinico = 
  ggplot(hazard_summarised_clin,aes(x = HR,y = catego_fac, col = names)) + 
  geom_rect(data=rects_clin, aes(xmin=-1.4, xmax=5, ymin=ystart,ymax=yend, fill=col), alpha =0.5,inherit.aes = F,show.legend = F) +
  geom_errorbarh(aes(xmin= low, xmax= high),position = position_dodge(.6),show.legend = F) +
  geom_vline(xintercept=1,linetype="dashed") + 
  geom_point(shape = 15, size = 3) +
  geom_label(aes(x=4.9,label = pvalue),size = 3,show.legend = F,hjust = "inward") +
  geom_label(aes(x=-1.3,label = ntext),size = 3, show.legend = F,hjust = "inward") +
  xlim(-1.4,5) + 
  ylab('Predictor') +
  xlab('Hazard Ratio') +
  scale_fill_discrete(type = c('gray','white')) +
  scale_color_discrete('Clustering factor',type  = brewer.pal(9,'Set1')[c(1:4)]) +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  ggtitle('Prognostic value of clinical variables')


#plot
predictor_patho = 
  ggplot(hazard_summarised_patho,aes(x = HR,y = catego_fac, col = names)) + 
  geom_rect(data=rects_path, aes(xmin=-1.6, xmax=10, ymin=ystart,ymax=yend, fill=col), alpha =0.5,inherit.aes = F,show.legend = F) +
  geom_errorbarh(aes(xmin= low, xmax= high),position = position_dodge(.6),show.legend = F) +
  geom_vline(xintercept=1,linetype="dashed") + 
  geom_point(shape = 15, size = 3) +
  geom_label(aes(x=9.9,label = pvalue),size = 3,show.legend = F,hjust = "inward") +
  geom_label(aes(x=-1.6,label = ntext),size = 3, show.legend = F,hjust = "inward") +
  xlim(-1.6,10) + 
  ylab('Predictor') +
  xlab('Hazard Ratio') +
  scale_fill_discrete(type = c('gray','white')) +
  scale_color_discrete('',type  = brewer.pal(9,'Set1')[c(5,7:9)]) +
#  scale_x_continuous(expand = c(0.01,0.01))
  theme_bw() + 
  theme(panel.grid.major = element_blank(),axis.title.y = element_blank(),panel.grid.minor = element_blank()) + 
  ggtitle('Prognostic value of pathological variables')


#plot
predictor_gexpr = 
  ggplot(hazard_summarised_gexpr,aes(x = HR,y = catego_renamed, col = names)) + 
  geom_rect(data=rects_Gxpr[[k]], aes(xmin=0, xmax=3.5, ymin=ystart,ymax=yend, fill=col), alpha =0.5,inherit.aes = F,show.legend = F) +
  geom_errorbarh(aes(xmin= low, xmax= high),position = position_dodge(.6),show.legend = F) +
  geom_vline(xintercept=1,linetype="dashed") + 
  geom_point(shape = 15, size = 3) +
  geom_label(aes(x=3.4,label = pvalue),size = 3,show.legend = F,hjust = "inward") +
  geom_label(aes(x=0.1,label = ntext),size = 3, show.legend = F,hjust = "inward") +
  xlim(0,3.5) + 
  ylab('Predictor') +
  xlab('Hazard Ratio') +
  scale_fill_discrete(type = c('gray','white')) +
  scale_color_discrete('Gene signature',type  = brewer.pal(9,'Set1')[c(1:5,7:9)]) +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  ggtitle('Prognostic value of gene expression clusters')


#
pdf(file.path(params$outputpath,paste0('Figure1_predictor_clinico_patho10Y.pdf')),width = 10,height = 5)
predictor_clinico + predictor_patho + plot_layout(guides = 'collect') + plot_annotation(tag_levels = 'A') 
dev.off()

#
#pdf(file.path(params$outputpath,ifelse(k==2,paste0('Figure5_predictor_clinico_gexpr_2_10Y.pdf'),paste0('FigureS2_predictor_clinico_gexpr_3_10Y.pdf'))),width = 7,height = 6) #predictor_gexpr
#dev.off()
```


```{r upset_plot, message= T}
clinical_cluster_upset = clinical_cluster[,colnames(clinical_cluster) %in% c('k2','k3','k4','Stage')]
rownames(clinical_cluster_upset) = rownames(clinical_cluster)

clinical_cluster_upset$`k = 2 (cluster 1)` = ifelse(clinical_cluster_upset$k2 ==tail(levels(clinical_cluster$k2),1),1,0)
clinical_cluster_upset$`k = 3 (cluster 3)` = ifelse(clinical_cluster_upset$k3 ==tail(levels(clinical_cluster$k3),1),1,0)
clinical_cluster_upset$`k = 4 (cluster 3)` = ifelse(clinical_cluster_upset$k4 ==tail(levels(clinical_cluster$k4),1),1,0)

clinical_cluster_upset$`patho stage 3-4` = ifelse(clinical_cluster_upset$Stage == 'stage 3-4',1,0)

upset_plot = upset(clinical_cluster_upset,colnames(clinical_cluster_upset)[5:7],
                   min_size = 0,
                   set_sizes=FALSE,
                   min_degree=1,
                   stripes=c('cornsilk1', 'grey90'),
                   matrix=(intersection_matrix() + scale_y_discrete(position='right')),
                   themes=upset_modify_themes(
        list(
            'intersections_matrix'=theme(text=element_text(size=12)),
            'Intersection size'= list(ylab('Number of patients'),ggtitle('Patients overlap in low survival clusters'))
        )
    ))
```


```{r venn}
library(VennDiagram)
 
# Generate 3 sets of 200 words
k2_clusterlow <- rownames(clinical_cluster)[clinical_cluster$k2==tail(levels(clinical_cluster$k2),1)]
k3_clusterlow <- rownames(clinical_cluster)[clinical_cluster$k3==tail(levels(clinical_cluster$k3),1)]
k4_clusterlow <- rownames(clinical_cluster)[clinical_cluster$k4==tail(levels(clinical_cluster$k4),1)]
stage34 <- rownames(clinical_cluster)[clinical_cluster$Stage=='stage 3-4']

x = list(k2_clusterlow,k3_clusterlow,k4_clusterlow)
names(x) = c('k = 2 (cluster 1)','k = 3 (cluster 3)','k = 4 (cluster 3)')


# Chart
venn_plot = ggvenn::ggvenn(
  x,padding = 0.1, 
  show_stats = 'c',
  fill_color = c("#0073C2FF", "#EFC000FF", "#868686FF", "#CD534CFF"),
  stroke_size = 0.5, set_name_size = 3,text_size = 4
  ) #+
 # ggtitle('Patients overlap in poor prognostic clusters\n(k = 2, k = 3, k = 4)')
```


```{r barplots}
clinical_cluster$survival = 'high'
clinical_cluster$survival [(clinical_cluster$k2 == tail(levels(clinical_cluster$k2),1)) &
                              (clinical_cluster$k3 == tail(levels(clinical_cluster$k3),1))
                               & (clinical_cluster$k4 == tail(levels(clinical_cluster$k4),1))] = 'low'

clinical_cluster$survival = factor(clinical_cluster$survival,levels = c('low','high'))

patho = clinical_cluster %>% 
  group_by(survival, Stage) %>% 
  summarise(len =length(Stage)) %>% 
  ggplot(aes(fill = Stage, x = len, y = survival)) + 
  geom_bar(position='fill', stat="identity") + 
  ylab('Survival group') +
  xlab('Proportions') +
# ggtitle('Poor (103 patients) vs.\ngood (412 patients) groups') +
  theme_bw() +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1))

sex = clinical_cluster %>% 
  group_by(survival, Sex) %>% 
  summarise(len =length(Sex)) %>% 
  ggplot(aes(fill = Sex, x = len, y = survival)) + 
  geom_bar(position='fill', stat="identity" ) + 
  ylab('Survival group') +
  xlab('Proportions') +
#  ggtitle('Sex') +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

smoke = clinical_cluster %>% 
  group_by(survival, `Smoking\nstatus`) %>% 
  summarise(len =length(`Smoking\nstatus`)) %>% 
  ggplot(aes(fill = `Smoking\nstatus`, x = len, y = survival)) + 
  geom_bar(position='fill', stat="identity") +
  ylab('Survival group') +
  xlab('Proportions') +
 # ggtitle('Smoking') +
  theme_bw() +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1))


grade = clinical_cluster %>% 
  filter(Grade != 'unknown') %>%
  group_by(survival, Grade) %>% 
  summarise(len =length(Grade)) %>% 
  ggplot(aes(fill = Grade, x = len, y = survival)) + 
  geom_bar(position='fill', stat="identity") +
  ylab('Survival group') +
  xlab('Proportions') +
#  ggtitle('Grade') +
  theme_bw() +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1))


feature = clinical_cluster %>% 
  filter(`Predominant\nfeature` != 'unknown') %>%
  group_by(survival, `Predominant\nfeature`) %>% 
  summarise(len =length(`Predominant\nfeature`)) %>% 
  ggplot(aes(fill = `Predominant\nfeature`, x = len, y = survival)) + 
  geom_bar(position='fill', stat="identity") +
  ylab('Survival group') +
  xlab('Proportions') +
#  ggtitle('Predominant pattern') +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


perctumor = clinical_cluster %>% 
  group_by(survival, `Percentage\nof Tumor`) %>% 
  summarise(len =length(`Percentage\nof Tumor`)) %>% 
  ggplot(aes(fill = `Percentage\nof Tumor`, x = len, y = survival)) + 
  geom_bar(position='fill', stat="identity") +
  ylab('Survival group') +
  xlab('Proportions') +
 # ggtitle('Percentage tumor') +
  theme_bw() +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1))

tumorvol = clinical_cluster %>% 
  group_by(survival, `Tumor volume\n(cm3)`) %>% 
  summarise(len =length(`Tumor volume\n(cm3)`)) %>% 
  ggplot(aes(fill = `Tumor volume\n(cm3)`, x = len, y = survival)) + 
  geom_bar(position='fill', stat="identity") +
  ylab('Survival group') +
  xlab('Proportions') +
 # ggtitle('Percentage tumor') +
  theme_bw() +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1))

#pdf(file.path(params$outputpath,paste0('Figure4_prognostic.pdf')),width = 14,height = 9)
#((venn_plot | patho | sex) + plot_layout(width = c(5,3.5,3.5))) / (smoke | grade | feature) #
#(venn_plot + patho + sex  + smoke + grade + feature) + plot_layout(height = c(4,4)) + plot_annotation(tag_levels = 'A')

#((upset_plot | venn_plot) + plot_layout(width = c(12,6)))/ ((patho | smoke | grade | feature) + plot_layout(width = c(4.5,4.5,4.5,4.5))) + plot_layout(height = c(4,4)) + plot_annotation(tag_levels = list(c('A','','B','C','D','E','F')))



pdf(file.path(params$outputpath,paste0('Figure4_prognostic2.pdf')),width = 14,height = 9)

(( pfits[[1]] / pfits[[2]] / pfits[[3]]) + plot_layout(height = c(3,3,3)) | (
  ((upset_plot | venn_plot) + plot_layout(width = c(4,3)) ) / ((sex | smoke | patho) / (feature | grade | tumorvol)))) + plot_layout(width = c(4,5))  + plot_annotation(tag_levels = list(c('A','B','C','D','E','','F','G','H','I','J','K')))

dev.off()
```



```{r degs, message= T, eval = F}
#small POC
clinical_cluster$survival

#
txi = readRDS(file.path(params$repo,'../rnaseq/lord_kallisto/txi.rds'))
clinical_bigtable = read.csv(file.path(params$repo,'../rnaseq/data/clinical_bigtable_v3.csv'), check.names = F)

#tumors only
txi$counts = txi$counts[,grep('Tumeur',colnames(txi$counts))]
txi$abundance = txi$abundance[,grep('Tumeur',colnames(txi$abundance))]
txi$length =txi$length[,grep('Tumeur',colnames(txi$length))]

#order things
order = order(sapply(strsplit(colnames(txi$counts), "_"), "[",5))
txi$counts = txi$counts[,order]
txi$abundance = txi$abundance[,order]
txi$length = txi$length[,order]
all.equal(as.character(clinical_cluster$`Record ID`),sapply(strsplit(colnames(txi$counts), "_"), "[",5))


#deseq object
dds = DESeqDataSetFromTximport(txi,colData = clinical_cluster, ~ survival)
#dds = DESeqDataSetFromTximport(txi,colData = clinical_bigtable_normal_tumor, ~ predominant_feature*tissue)
     dds = DESeq(dds)
     resultsNames(dds)
     #predominant_feature_Acinar_vs_
     #predominant_featureAcinar.tissueTumeur
     res = results(dds)#,name=c('tissueTumeur.predominant_featureAcinar'))
     res = res[order(res$pvalue),] #order by pval
     res = res[res$baseMean>0,] #remove 0 expression values
     res = res[!is.na(res$padj),] #remove NA
     #dim(res)
     #head(res)
     res_signif = res[res$padj<0.05,]
     dim(res_signif)
     
     
#GO 
gene_list = rep(1,nrow(res))
gene_list[res$padj<0.05] = 0

names(gene_list) = sapply(strsplit(rownames(res), ".",fixed = T), "[",1)

  GOdata <- suppressMessages(new("topGOdata",
              ontology = "BP",
              allGenes = gene_list,
              geneSel = function(x=gene_list){y = rep(TRUE,length(x));y[x==1]=FALSE;names(y) = names(x);return(y)},
              description = "GO analysis of DEGs",
              annot = annFUN.org,mapping = "org.Hs.eg.db",ID = 'ensembl'))
  
  resultFis <- suppressWarnings(suppressMessages(runTest(GOdata, algorithm = "classic", statistic = "fisher")))

  temp = GenTable(GOdata, resultFis, topNodes = length(resultFis@score)) 
  
  temp = temp[(temp$Expected>1) & (temp$Significant>0) & (as.numeric(temp$result1)<0.99),]
  
  temp$padj = signif(p.adjust(as.numeric(temp$result1),method = 'fdr'),4)
  
  temp = temp[temp$padj < 0.1,]
  temp$FoldChange = signif(temp$Significant/temp$Expected,2)
  head(temp,5)[order(head(temp,5)$FoldChange,decreasing=F),]
       
  
     
```



# save it
```{r session, message= T,eval = F}
#save it 
pdf(file.path(params$outputpath,paste0('Figure3_survival.pdf')),width = 12,height = 8)
pfits[[4]] + pfits[[1]] + pfits[[2]] + pfits[[3]] + plot_annotation(tag_levels = 'A')
dev.off()
```


# session info 
```{r session, message= T}
sessionInfo()
```
     
     
